version: '1.0'
name: fastapi-classifier
displayName: fastapi-classifier
triggers:
  push:
    - matchType: REGEX
      branch: ^master$
stages:
  - name: test-stage
    displayName: test-stage
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: run-tests
        displayName: run-tests
        pythonVersion: '3.10'
        commands:
          - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
          - pytest tests/ -v
          
  - name: docker-stage
    displayName: docker-stage
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build-image
        displayName: build-image
        dockerfile: Dockerfile
        imageName: fastapi-classifier
        imageTag: latest